services:
  - type: web
    name: todolist-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
